version: "3.7"

services:

  identificacao:
    #build:
    #  context: ../
    #  dockerfile: ./docker/Dockerfile
    image: unbmaster/identificacao:44
    container_name: identificacao
    volumes:
      - ../:/var/www
      - app-data:/var/lib/data
    ports:
      - "4488:443"
    restart: always
    networks:
      - app-net

networks:
  app-net:
    external: true

volumes:
  app-data: